# Generated by Django 3.2.5 on 2021-08-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0002_auto_20210818_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='dia_chi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='gioi_tinh',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
