# Generated by Django 3.2.5 on 2021-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=80, null=True)),
                ('material_name', models.CharField(max_length=80)),
                ('maker', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
                ('buying_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('status', models.CharField(max_length=80)),
            ],
        ),
    ]
