# Generated by Django 3.2.5 on 2021-08-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='accept_card',
            field=models.CharField(default='NO', max_length=50),
        ),
    ]
